name: ansible 

# Allow repository modyfication;
permissions:
  packages: write

on:
  # Allow to re-use this jobs;
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Build 
        run: |
          make 

      - name: Get latest tag
        id: get_tag
        run: echo ::set-output name=TAG::$(git describe --tags --abbrev=0)
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG }}
          release_name: Release ${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false

      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ansible/rootfs.tar.xz
          asset_name: ${{ github.event.repository.name }}-${{ steps.get_tag.outputs.TAG }}.tar.xz
          asset_content_type: application/x-xz

