name: ansible 

on:
  push:
    branches:
      - develop

jobs:
  report:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Build 
        run: |
          make 

      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_path: ./ansible/rootfs.tar.xz
          asset_name: rootfs.tar.xz
          asset_content_type: application/gzip
