name: build 

# Allow repository modyfication;
permissions:
  contents: write

on:
  # Allow to re-use this jobs;
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: 'Prepare'
        run: |
          #make prepare 

      - name: 'Execute'
        run: |
          #make execute 
          cd ansible;
          dd if=/dev/zero of=rootfs.tar.xz  bs=1024  count=10240

      - name: 'Release'
        run: |
            
            cd ansible;
            TAG="$(git ls-remote -q --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//')"

            NEW_NAME="${{ github.event.repository.name }}-${TAG}";
            NEW_NAME="${NEW_NAME//[^[:alnum:]]/_}"

            mv rootfs.tar.xz ${NEW_NAME};
            gh release create ${TAG} ${NEW_NAME}.tar.xz;

        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

