name: execute 

# Allow repository modyfication;
permissions:
  contents: write

on:
  # Allow to re-use this jobs;
  workflow_call:

jobs:
  execute:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: Prepare 
        run: |
          make execute 
