name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
    paths:
      - ansible/**
  # Trigger manually;
  workflow_dispatch:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# BUILD 
# -----------------

  prepare:
    needs: semver
    uses: "./.github/workflows/build.yml"

