name: workflow 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write
  packages: write

on:
  # Trigger automaticly;  
  push:
  # Trigger manually;
  workflow_dispatch:

jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/tagging.yml@feat/output

# -----------------
# PREPARE 
# -----------------

  prepare:
    needs: semver
    uses: "./.github/workflows/prepare.yml"

# -----------------
# EXECUTE 
# -----------------

  execute:
    needs: prepare 
    uses: "./.github/workflows/execute.yml"

# -----------------
# PUBLISH 
# -----------------
#
  publish:
    needs: execute 
    uses: "./.github/workflows/publish.yml"
